use Case_study_1 
go

select * from dbo.fact;

select * from dbo.Location;

select * from dbo.product;

-----------------------------------------------------------------------------------------------------------
--1. Display the number of states present in the LocationTable?
select count(Distinct state) from dbo.Location

--2. How many products are of regular type?
select product from dbo.Product
where Type = 'Regular'

--3. How much spending has been done on marketing of product Id 1?
select sum( marketing) as total_marketing from fact
where ProductId = '1' 

--4. What is the minimum sales of a product?
select min(Sales) as min_sales from fact

--5.Display the max Cost of Good Sold (COGS)

select max(COGS) AS MAX_COGS FROM fact

--6. Display the details of the product where product type is coffe

select productid,Product from Product
where Product_Type = 'coffee'

--7. Display the details where total expenses are greater than 40?
select Total_Expenses from fact
where Total_Expenses > 40

--8.What is the average sales in area code 719?
select avg(sales) from fact
where Area_Code = '719'

--9. Find out the total profit generated by Colorado state?
select sum(f.Profit) as total_profit from fact f
inner join dbo.Location L on
f.Area_Code = L.Area_Code
where L.State = 'Colorado'

--10. Display the average inventory for each product ID? 
select ProductId, avg(Inventory) as avg_inventory from fact
group by  ProductId

--11.Display state in a sequential order in a  Location Table?
select Distinct State from dbo.Location
order by state 

--12. Display the average budget of the Product where the average budget margin should be greater than 100?
select ProductId, avg(Budget_Margin) as avg_margin  from fact
group by ProductId
having avg( Budget_Margin ) > 100

--13. What is the total sales done on date 2010-01-01?
select sum(sales) as total_sales from fact
where date = '2010-01-01'

--14. Display the average total expense of each product ID on an individual date?
select Date,ProductId,avg(Total_Expenses)as avg_expenses from fact
group by Date,ProductId

--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code?

select f.date, f.productID, p.product_type, p.product, f.sales, f.profit, l.state, f.area_code from fact f
join Product P on f.productID =  p.ProductId
join Location L on f.area_code = L.Area_Code

--16.Display the rank without any gap to show the sales wise rank?
select *,DENSE_RANK() OVER (order by sales asc) 
as Sales_RANK from dbo.fact;

--17. Find the state wise profit and sales?
select L.state, 
sum(f.Sales) as total_sales,
sum(f.Profit) as total_profit 
from fact f
join dbo.Location L on f.Area_Code = L.Area_code
group by l.State
order by total_sales desc

--18. Find the state wise profit and sales along with the productname? 
select L.state, P.Product,
sum(f.Sales) as total_sales,
sum(f.Profit) as total_profit 
from fact f
join dbo.Location L on f.Area_Code = L.Area_code
join dbo.Product P on f.ProductId = P.ProductId
group by l.State, P.Product
order by total_sales desc

--19. If there is an increase in sales of 5%, calculate the increasedsales?
select ProductId,sales, sales*1.05 as Increased_sale from fact

--20. Find the maximum profit along with the product ID and producttype. 

select top 1 f.productid, p.product_type, f.profit from fact f
join product p on f.productid = p.productid 
order by f.profit desc;

--21. Create a stored procedure to fetch the result according to the product typefrom Product Table.
create procedure get_products @product_type varchar(40)
as
begin
select * from product where product_type = @product_type;
end;
exec get_products 'coffee';

--22. Write a query by creating a condition in which if 
--the total expenses isless than 60 then it is a profit or else loss.

select 
	Total_Expenses,
CASE  
	when Total_Expenses < 60 then 'profit'
	else 'loss'
END AS RESULT

from fact

--23. Give the total weekly sales value with the date and product IDdetails. Use
-- roll-up to pull the data in hierarchical order.
SELECT
    DATEPART(WEEK, [date]) AS Weekly_Order,
    [date],
    ProductID,
    SUM(Sales) AS Total_Sales
FROM fact
GROUP BY
    ROLLUP (
        DATEPART(WEEK, [date]),
        [date],
        ProductID
    )
ORDER BY
    Weekly_Order,
    [date],
    ProductID;

--24. Apply union and intersection operator on the tables which consistofattribute area code.
select Area_Code from fact f
union 
select Area_Code  from Location L

select Area_Code from fact f
intersect
select Area_Code  from Location L

--25. Create a user-defined function for the product table to fetch a particular 
--product type based upon the user’s preference.

create function dbo.fun_product(@Product nvarchar(max))
returns varchar(max)
as
begin
    return (
     case
                when @product like '%Decaf%' then 'Decaf'
                else 'Regular'
     end
     )
end;

--26. Change the product type from coffee to tea where product ID is 1 and undo it?
begin tran;

update Product
set Product_Type = 'tea' from Product
where ProductId = 1

rollback;

--27. Display the date, product ID and sales where total expenses are between 100 to 200.
select Date,ProductId,Sales
from fact
where Total_Expenses between 100 and 200

--28. Delete the records in the Product Table for regulartype.
select * from Product
--begin tran;

delete from Product
where Type = 'Regular'

--rollback;

--29. Display the ASCII value of the fifth character from the columnProduct
select ASCII ('U') as product_ascii